# Playbook for Ubuntu packages update
# Execution:  ansible-playbook ubuntu-update.yml -i hosts
---
- hosts: web1
  become: yes
  become_method: sudo
  tasks:
    - name: Update cache
      apt:
        update_cache: yes

    - name: Update all packages to the latest version
      apt:
        upgrade: dist

    - name: Reboot host
      shell: shutdown -r now

    - name: Wait for server to come back after reboot
      pause:
        seconds: 30

    - name: Check for server
      local_action: shell ansible -u {{ ansible_user_id }} -m ping {{ inventory_hostname }} -k
      register: result
      until: result.rc == 0
      retries: 30
      delay: 10

    - name: Simple uptime touch
      shell: uptime
