# Playbook for Ubuntu16.04 update and reboot
# Execution:  ansible-playbook ubuntu-update.yml -i hosts -k
---
- hosts: all
  become: yes
  become_method: sudo

  tasks:
    - name: Update cache
      apt:
        update_cache: yes

    - name: Update all packages to the latest version
      apt:
        upgrade: dist
      register: apt_upgrade

    - debug: msg='{{ apt_upgrade.stdout.split('\n')[4] }}'

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot server
      shell: sleep 2 && shutdown -r now "Ansible reboot"
      async: 1
      poll: 0
      ignore_errors: true
      when: reboot_required_file.stat.exists

    - name: Wait for server to come up
      wait_for_connection:
        delay: 75
      when: reboot_required_file.stat.exists

    - name: Show server uptime
      shell: uptime
      register: uptime

    - debug: msg='{{ uptime.stdout }}'

